### ISSUE TITLE
Add LICENSE file to repository, add to MANIFEST.in

### ISSUE THREAD

**Issue by koobs** [takemaru/graphillion#19]
Add a LICENSE file to the repository. Useful for downstream OS packagers/porters to include it in OS packages.

- [x] LICENSE: Header contains Copyright notice
- [x] LICENSE: MIT License content
- [x] Add to MANIFEST.in, so to include it in PyPI sdist

**Comment by takemaru** [comment]
Thank you for suggesting the license clarification.  The updated version is now released as v0.99 and is found in PyPI as well.

**Comment by koobs** [comment]
Thanks! :)

**Comment by koobs** [comment]
Added in https://github.com/takemaru/graphillion/commit/b205180f1c035c1bfc51701d75d406669bb0e64c
