### ISSUE TITLE
DAG 

### ISSUE THREAD

**Issue by hotpeperoncino** [takemaru/graphillion#29]
I'd like to use one way direction edge in graph in case of finding all pathes.
 Probably as default behavior, this library computes
on bidirectional graph.  when some edges have only one direction, how to support them in
program ? can I have your advice?

**Comment by takemaru** [comment]
As you guessed, Graphillion currently supports undirected graphs only.  If you only want to enumerate/count paths in a directed graph, you can use the following implementation:

https://github.com/junkawahara/frontier

Best regards,

**Comment by hotpeperoncino** [comment]
Thank you for your reply and information. I want to do intersection operation between several results.
I'd like to investigate the introduced library, thanks.

**Comment by moh55m55** [comment]
I have the same issue @hotpeperoncino (i.e.,  finding all paths). Did you find the aforementioned lib useful? Or direct me to any useful resource, please. Thanks @takemaru for making the graphillion available.

**Comment by takemaru** [comment]
Although I haven't used the lib, the developer of the lib is one of Graphillion founders, so I believe it is useful for Graphillion users.
