### ISSUE TITLE
how to create a graph faslty from a BIG file with graphillion!!??

### ISSUE THREAD

**Issue by AsmaZbt** [takemaru/graphillion#31]
hello! 
I have a file of 1Gb , the format of each line be like this : 
word1       word2      distance 
i would like to creat an undirected graph of the related words quicly , 

i've using this function 
G = nx.read_edgelist("neighbours.txt", delimiter="\t", data=[("weight", float)])
it's work BUT  1h45mn to build the graph it's too much , i don't have too much time , i have lot of files to do the same process with them :( 

can I do that faslty with graphillion??

**Comment by takemaru** [comment]
Thank you for using Graphillion.
Since your question is about networkx, I recommend you to ask on the site of networkx.

Best regards,

**Comment by ReblochonMasque** [comment]
Maybe the question was: Can this be done with Graphillion efficiently, instead of using NetworkX?

**Comment by takemaru** [comment]
Sorry, I misread.
Unfortunately, Graphillion isn’t faster than networkx for creating a *single* graph.  Graphillion is designed to efficiently handle a large *set* of graphs (in other words, to handle complicated constraints such as s-t path).

**Comment by ReblochonMasque** [comment]
Thank you for this clarification!

**Comment by AsmaZbt** [comment]
Thank you so much , i'm sorry for the non clear question (my english is not very good) thanks for @ReblochonMasque to clarify my question , that was exactly my question. 


Thanks Takemaru for the clear answer.
