### ISSUE TITLE
Python Dict Memo Caching or Memoization

### ISSUE THREAD

**Issue by seanlaw** [takemaru/graphillion#35]
I would like to create a dictionary where I specify keys that point to different individual subgraphs within the Graphset. For example,

    memo = {}
    universe = [(0,1), (1,2), (2,3), (3,4), (0,2)]
    GraphSet.set_universe(universe)
    gs = GraphSet()

    gs.add([(0,1), (1,2)])
    memo['sub1'] = direct reference to subgraph [(0,1), (1,2)] within gs and not a copy

    gs.add([(0, 2), (2, 3)])
    memo['sub2'] = direct reference to subgraph [(0, 2), (2, 3)] within gs and not a copy

    gs.add([(1, 2), (2, 3), (3, 4)])
    memo['sub3'] = direct reference to subgraph [(1, 2), (2, 3), (3, 4)] within gs and not a copy

Is this possible in graphillion?

**Comment by takemaru** [comment]
I guess you expect the following behavior.

`
memo['sub1'] = get_reference_from(gs, [(0,1), (1,2)])
update(memo['sub1'])  # updates `gs` as well
`

If so, it's impossible in Graphillion.  Because graphs are not explicitly maintained in Graphillion, and cannot get their references.

**Comment by seanlaw** [comment]
Thank you. I am trying to reproduce [the paper "Dancing with Decision Diagrams: A Combined Approach to Exact Cover"](https://aaai.org/ocs/index.php/AAAI/AAAI17/paper/download/14907/13855) by Nishino, Minatom  _et _al__ where they develop the DXZ algorithm utilizing ZDD. Maybe I am thinking about it incorrectly but I was hoping that Graphillion can be used to enumerate all of the set of solutions in their paper. Can you tell me whether or not Graphillion is the right tool for the job?

**Comment by seanlaw** [comment]
Actually, for each subgraph that gets added into the GraphSet, I want to be able to quickly retrieve the subgraph from the GraphSet. This way, I don't have to store individual subgraphs in the dictionary. So, following my example above, I want to be able to do something like

    print(memo['sub1'])  #  prints [(0,1), (1,2)]

Or define a function that can print the subgraph given a dictionary key:


    def print_subgraph(some_key):
        print(memo[some_key])

    print_subgraph('sub1')  #  prints [(0,1), (1,2)]

**Comment by seanlaw** [comment]
Even with `update` I am hitting 11 GB of memory reached within a few minutes. In my universe, I have 61,075 possible edges. At each update, I am adding a GraphSet that contains a single subgraph composed of only nine connected edges. I estimate that I have roughly 10-100 trillion individual subgraphs that will need to be updated.

**Comment by takemaru** [comment]
Sorry, I forgot to mention the memory issue.

The compression ratio of Graphillion depends on the complexity of the set.  For such a large universe (a graph with tens of thousands of edges), Graphillion could require tens of GB of memory, if the set were somewhat complicated.  I'm afraid that your graph set is rather complex.  If so, it is very hard to compress it even with another compression scheme.

**Comment by takemaru** [comment]
If the set should be compressed compactly according to the dancing link paper, please ask Nishino-san.

**Comment by seanlaw** [comment]
So, I've moved my computation over to a machine with 64 GB of RAM and I notice that the memory usage stays around 47 GB. Sometimes, the memory usage increases to 52 GB for a few minutes and then it drops back down to ~47 GB. This implies that Graphillion is occasionally optimizing the ZDD or underlying graph structure. Is my understanding correct?

**Comment by takemaru** [comment]
Graphillion does not do any memory optimization (e.g. garbage collection), but the Python runtime sometimes does.  So, the behavior can be caused by Python, I think.
