### ISSUE TITLE
Store Path Counts in Graphillion

### ISSUE THREAD

**Issue by seanlaw** [takemaru/graphillion#40]
Let's say that I have 8 paths/sequences where each number represents a node:

```
x = [[1, 2, 3, 4, 5], 
     [8, 9, 10], 
     [4, 6, 8, 10], 
     [1, 2, 3, 4, 5], 
     [8, 9, 10], 
     [11, 13, 14, 16],
     [1, 2, 3],
     [9, 10]
    ]
```

Is there a way to push these into a graph using Graphillion and then be able to keep track of the fact that paths `[1, 2, 3, 4, 5]` and `[8, 9, 10]` each have a count of `2` (i.e., these two paths are observed twice) while the other 6 paths have a count of `1`?

In my case, I don't know ahead of time that, say, `[1, 2, 3, 4, 5]` is counted twice since the data is large so I would need a way to update the count as new data is being read. Is this possible with Graphillion?

**Comment by takemaru** [comment]
Let me know your conditions in detail.

- Do you have too many paths to be stored as `dict`? (i.e. billions of paths)
- Approximated counts are acceptable? Or exact counts are required for all paths?
- Is the base/universe graph is fixed or dynamic?

**Comment by seanlaw** [comment]
>Do you have too many paths to be stored as dict? (i.e. billions of paths)
Yes, the paths are in the millions to likely billions and I want to reduce the memory consumption using ZDD

>Approximated counts are acceptable? Or exact counts are required for all paths?
Approximated counts are acceptable if there is a guarantee in terms of error bounds. I would like to know like to know relative percentages or be able to ask "which paths make up the top 10-20% of paths"

>Is the base/universe graph is fixed or dynamic?
Universe is fixed. At least, I can determine the universe of nodes beforehand. Are negative integers allowed as node numbers?

**Comment by takemaru** [comment]
I think that counting sketch is an appropriate technique for your requirements.  Counting sketch is a data structure used to approximately maintain many counters in small memory.  This technique has been developed in computer networking community for flow monitoring.  There are some open-sourced implementation, as follows:

- https://github.com/harvard-cns/opensketch
- https://github.com/ranbenbasat/RHHH

A related research paper is found at https://dlnext.acm.org/doi/abs/10.1145/3341302.3342076 .

**Comment by takemaru** [comment]
Negative numbers can be used as node names in Graphillion.  Actually, any hashable objects can be used.

**Comment by seanlaw** [comment]
I don't really understand the counting sketch work but it sounds like you would not recommend Graphillion for this?

**Comment by takemaru** [comment]
No.  ZDD, the internal structure of Graphillion, represents a _set of sets_.  From the mathematical definition, elements in a set cannot be duplicated, i.e., every element accounts for one or zero in a set.  This implies that ZDD cannot be used to count elements, though ZDD is good at computing the _size_ of a set (the number of elements in a set).

In other words, if you want to count the number of subsets (or that of subgraphs) satisfying given constraints, ZDD is a good tool.  However, if you want to associate a number with each element, ZDD doesn't work.

**Comment by takemaru** [comment]
There is a solution to utilize ZDD as counters, that is, ZDD vector or ZDD base, but counting sketch is more efficient if approximation is allowed.

**Comment by seanlaw** [comment]
That makes sense. Thank you!
