### ISSUE TITLE
ImportError: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev

### ISSUE THREAD

**Issue by dfajita** [takemaru/graphillion#42]
I have trouble with the following error when importing a graphillion.

```
Python 3.7.0 (default, Jun 28 2018, 13:15:42)
[GCC 7.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import graphillion
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/graphillion/__init__.py", line 27, in <module>
    from graphillion.setset import setset
  File "/home/user/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/graphillion/setset.py", line 25, in <module>
    import _graphillion
ImportError: /home/user/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/_graphillion.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev
```

My environment is
> OS: Ubuntu 20.04.1 LTS
> Python: Python 3.7.0 (pyenv: anaconda3-5.3.1)

The OS has just been cleanly installed.
The environment has barely changed from the default state.

I installed Graphillion by the following command.
```
pip install graphillion
```

I also tried installing from the source code, but ended up with the same error.

I would appreciate it if somebody could help me out.

**Comment by takemaru** [comment]
Thank you for using Graphillion.

It seems that linked libraries can't be found.
Can you properly install other modules that require C/C++ compilation, such as numpy?

**Comment by dfajita** [comment]
Thank you for replying to me.

Seems like the anaconda environment on pyenv is doing something wrong.
As for numpy, I haven't had any problems with it, as it's in anaconda by default.
It may be worth noting that no error has occurred during pip install of graphillion.

When the error occurred, I did a google search with the query 
"ImportError: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev". 
I then noticed that there are some reports with the exact same import error message.
But because those reports took a higher-level approach to solve the problem, I couldn't find a good way to solve my specific problem.
e.g.) https://stackoverflow.com/questions/58188230/headless-chrome-in-docker-symbol-not-found-error-after-latest-update

From this error message, could you determine which library is missing specifically?

**Comment by takemaru** [comment]
I'm not sure, but since the error says ostringstream, I'm guessing that your anaconda environment doesn't link the C++ STL properly?

**Comment by dfajita** [comment]
As you point out, this seems to be a compatibility issue with the anaconda environment, so I decided not to pursue it in depth. Fortunately, I've found it works fine in my regular non-Anaconda Python environment. I do appreciate your kind support.
