### ISSUE TITLE
GraphSet([[]]).min_iter() should return the set consisting of the empty graph but not so.

### ISSUE THREAD

**Issue by junkawahara** [takemaru/graphillion#45]
The following code should print '[[]]' (the set consisting of the empty graph) but actually
it prints '[]' (the empty set) in the current version.

```
gs = GraphSet([[]])
print(list(gs.min_iter()))
```

Note that the below code correctly outputs the answer.
```
GraphSet.set_universe([(1,2)])
gs = GraphSet([[], [(1,2)]])
print(list(gs.min_iter()))   # correctly output '[[], [(1, 2)]]'
```

**Comment by takemaru** [comment]
Thank you.
I merged the request and released the fixed version as v1.4.
