### ISSUE TITLE
how can I call zdd  library from graphillion 

### ISSUE THREAD

**Issue by bounabbessis** [takemaru/graphillion#59]
Dear all

I would like to use only the zdd part from graphillion  for set manipulation and not a graph . Since graphillion requests to use edges as tuples in the graph but in my case i don't need edges i need the structure of zdd and operation on zdd only using python.
how can i call the zdd from graphillion.
waiting to hear from you soon ;

Best Regards

**Comment by takemaru** [comment]
If you need to manipulate a "family of sets" and don't need ZDDs, you can use `graphillion.setset` class instead of `graphillion.GraphSet`.
If you really need ZDDs, unfortunately we don't provide any Python interface for them; ZDDs are handled only in the Internal C++.

**Comment by bounabbessis** [comment]
unfortunately i need zdds
Many thanks for your reply

Le lun. 28 juin 2021 à 05:34, Takeru Inoue ***@***.***> a
écrit :

**Comment by bounabbessis** [comment]
is setset represented as zdds ?

**Comment by takemaru** [comment]
`setset` is represented by ZDDs internally (i.e., C++); actually, `GraphSet` is just a wrapper class on `setset`.
