### ISSUE TITLE
setset load does not work problem 

### ISSUE THREAD

**Issue by bounabbessis** [takemaru/graphillion#60]
dear all ;

when i dump a setset  MM in file  like this : 
with open('statespace.data', 'wb') as f:        
    MM.dump(f)
 

satespace file looks like this 

1211954 511 B T
1211440 510 B T
1179340 509 B T
1178184 508 B T
1094540 507 B T
1093960 506 B T
1079978 505 B T
1078212 504 B T
.....

when i want to load it it does not work 
f=open('statespace.data', 'rb')
gs.load(f)
please I need help

**Comment by bounabbessis** [comment]
dear Prof Takemaru
when I load, i don't get the same [data](url) dumped but instead i get like an ID 
[totakemaru.pdf](https://github.com/takemaru/graphillion/files/6735355/totakemaru.pdf)
could you help me please

**Comment by bounabbessis** [comment]
I still waiting your help

**Comment by takemaru** [comment]
Thank you.
This is a bug.

Until fixing it, I'll give you a workaround: wrap the loaded object by `setset` constructor,
`ss = setset(setset.load(f))`

**Comment by bounabbessis** [comment]
ss = setset(setset.load(f))
 many thanks it works very fine .

**Comment by takemaru** [comment]
Re-opened for fixing it later.

**Comment by bounabbessis** [comment]
I draw your attention that
ss = setset(setset.load(f))

work only in the same notebook . but if i load it in a notebook different that the notebook where i have dump data it does not work and raise an error  out of index  even if i do f.seek(0) before load the problem remain.

**Comment by takemaru** [comment]
I fixed the bug.
Please update Graphillion to v1.5; e.g., `pip install graphillion==1.5`

**Comment by takemaru** [comment]
Oops, not yet fixed...

**Comment by bounabbessis** [comment]
Dear Prof Takeru;

I need your email to discuss a scientific subject with you. This subject is
Pspace complete but as you know even, in temporal complexity, if the
problem is NP-complete there is an efficient application for solving it for
that reason. Maybe using zdd  we can take the solution to its limit if
possible .

waiting to hear from you soon

Best Regards

Le ven. 9 juil. 2021 à 16:15, Takeru Inoue ***@***.***> a
écrit :

**Comment by takemaru** [comment]
Sorry but I don't have time to be involved in other projects. I hope to hear interesting results from you.

**Comment by bounabbessis** [comment]
Many Thanks Prof Takeru. I apologize if I have wasted your time.
Graphillion is magic . The reason for My suggestion is that you claim that
Graphillion can treat trillion of trillion of sub graphs . But in my case
it reach 27 million cliques it stops for that reason I was interested to
dive in the c++ implementation to understand it and use it directly  maybe
the problem with me is python as I have seen from the
previous  problem with setset loading
Best Regards

Le sam. 10 juil. 2021 à 15:24, Takeru Inoue ***@***.***> a
écrit :

**Comment by bounabbessis** [comment]
.....................................

bouneb would like to stay in touch on LinkedIn.

bouneb zine el abidine
Ingénieur chez etrag
Algeria

View profile https://www.linkedin.com/comm/in/bouneb-zine-el-abidine-48a32a209?trk=eml-guest-invite-pprofile-link-cta&trkEmail=eml-email_m2g_invite_single_01-null-373-null-null-%7E4zuwsj%7Ekvnji5vu%7Eq4-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BdRkrDkX2T5WxH3Rl3yQLQw%3D%3D

Confirm that you know bouneb https://www.linkedin.com/e/v2?e=-4zuwsj-kvnji5vu-q4&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BdRkrDkX2T5WxH3Rl3yQLQw%3D%3D&t=suwj&tracking=eml-guest-invite-cta&ek=email_m2g_invite_single_01&validationToken=1AcPkjcc&invitationId=6862665637228105728


.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-4zuwsj-kvnji5vu-q4&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_m2g_invite_single_01&li=381&m=unsub&ts=unsub&loid=AQFAu4PR1My4agAAAXz0WJBvNjIYKHjsYJYt08CtUMOS9rafG6NyRDPQnLNQWwtTea0VtJhtz81mjPF1snxT7Ta5c8w1G2yQJ59nsroLCsUGNOZj6vHmPNNaWC3iZPC7_OASDQ5z4PTBA2xaaQmGaX1xzJYgY3OkxA&eid=-4zuwsj-kvnji5vu-q4

Help: https://www.linkedin.com/e/v2?e=-4zuwsj-kvnji5vu-q4&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BdRkrDkX2T5WxH3Rl3yQLQw%3D%3D&a=customerServiceUrl&ek=email_m2g_invite_single_01&li=380&m=footer&ts=help&articleId=67


You are receiving Invitation emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to ***@***.***

© 2021 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by bounabbessis** [comment]
Hi ,

bouneb would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-4zuwsj-kvva5nhq-s7&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3BEEo0CfHlTuuEVGBZZYUHWw%3D%3D&t=suwj&ek=email_first_guest_reminder_03&li=20&m=hero&ts=accept_text

View bouneb’s profile: https://www.linkedin.com/comm/in/bouneb-zine-el-abidine-48a32a209?trk=eml-email_first_guest_reminder_03-hero-2-prof%7Ename&trkEmail=eml-email_first_guest_reminder_03-hero-2-prof%7Ename-null-%7E4zuwsj%7Ekvva5nhq%7Es7-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3BEEo0CfHlTuuEVGBZZYUHWw%3D%3D



.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-4zuwsj-kvva5nhq-s7&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_first_guest_reminder_03&li=17&m=unsub&ts=unsub&loid=AQFz-jlnLD-xOwAAAX0QPh0kYb3USUFJ0aPdBXed0u3EAwVrv1gXP0tBvWeGuxAMfTlTTvsIlmwV4XzxvWLgqfuWUK5U2ifWs748gnzFRTV_hPugxk3fvZjgjlJVVKFYMt3DTcORSptiMXwFiZqM5E1IydnayePgyfbXiw&eid=-4zuwsj-kvva5nhq-s7

Help: https://www.linkedin.com/e/v2?e=-4zuwsj-kvva5nhq-s7&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3BEEo0CfHlTuuEVGBZZYUHWw%3D%3D&a=customerServiceUrl&ek=email_first_guest_reminder_03&li=16&m=footer&ts=help&articleId=67


 LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to ***@***.***

© 2021 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by bounabbessis** [comment]
https://www.linkedin.com/e/v2?e=-4zuwsj-kw5anun5-8j&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3BVeVRY%2FklRRqDL%2FZtxjzxgw%3D%3D&t=suwj&ek=email_second_guest_reminder_03&li=11&m=hero&ts=accept_text

 https://www.linkedin.com/comm/in/bouneb-zine-el-abidine-48a32a209?trk=eml-email_second_guest_reminder_03-hero-2-prof%7Ename&trkEmail=eml-email_second_guest_reminder_03-hero-2-prof%7Ename-null-%7E4zuwsj%7Ekw5anun5%7E8j-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3BVeVRY%2FklRRqDL%2FZtxjzxgw%3D%3D



.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-4zuwsj-kw5anun5-8j&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_second_guest_reminder_03&li=8&m=unsub&ts=unsub&loid=AQGEF4yfhRHnvgAAAX00VXoroMjHSYYWUa7PTTR6AmOT5QFkCeaAJ2fTMPyv41fNrb1FE3_Cxx-XsrZzRp5dQI-VQ41m3vbWPne5yVs6Tb77PNQ7KnMtrWdOfWkOq3_b1gnz63URBbtTbvAbH7oaheLiB3yfH8BPv1vBRA&eid=-4zuwsj-kw5anun5-8j

Help: https://www.linkedin.com/e/v2?e=-4zuwsj-kw5anun5-8j&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3BVeVRY%2FklRRqDL%2FZtxjzxgw%3D%3D&a=customerServiceUrl&ek=email_second_guest_reminder_03&li=7&m=footer&ts=help&articleId=67


You are receiving Invitation reminder email emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to ***@***.***

© 2021 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
