### ISSUE TITLE
Exclude graph with depth?

### ISSUE THREAD

**Issue by reo-g** [takemaru/graphillion#71]
I would like to use ZDD for network optimization. Graphillion is really convenient for handling ZDDs in Python. When constructing a spanning forest, I would like to eliminate graph structures with greater depth rather than larger size. 
Is it possible to exclude graphs that contain depths exceeding a specified value when enumerating spanning forests?
Thanks.

**Comment by takemaru** [comment]
The following code builds the set of spanning forests excluding paths from the roots (1 and 16) longer than three edges.
```python
from graphillion import GraphSet
import graphillion.tutorial as tl 

universe = tl.grid(3, 3)
GraphSet.set_universe(universe)

forests = GraphSet.forests(roots=[1, 16], is_spanning=True)
long_paths = GraphSet.paths(terminal1=1).larger(3) | GraphSet.paths(terminal1=16).larger(3)
short_forests = forests.excluding(long_paths)

tl.draw(short_forests.choice())
```

**Comment by reo-g** [comment]
@takemaru 

Thank you very much for your polite response. 
I would like to set a limit based on Depth rather than the number of Edges when a node can have multiple elements. 
For example, if I want to limit it to Depth 3 or less, it would be acceptable if the Root has four direct children, but I would like to exclude cases where there are four nodes connected in a chain.

**Comment by takemaru** [comment]
Could you formally define Depth?

**Comment by reo-g** [comment]
I apologize for not being able to explain using graph-theoretical terms.

As a specific example, I would like to limit the maximum hop count in a wireless multi-hop network. For instance, any node in the spanning forest must be able to reach the Root within a specified number of hops. I want to enumerate network configurations in which any node from the Root forms a spanning forest that is within the maximum hop count.

**Comment by takemaru** [comment]
I think my example works for you, since it finds trees where the path length from the roots are limited to three or less.

**Comment by reo-g** [comment]
@takemaru I initially thought it wasn’t working due to an error, but it turned out to be an issue specific to the Windows environment. 
```
7 forests = GraphSet.forests(roots=[1, 16], is_spanning=True)
----> 8 long_paths = GraphSet.paths(terminal1=1).larger(3) | GraphSet.paths(terminal1=16).larger(3)
      9 short_forests = forests.excluding(long_paths)
     10 

TypeError: paths() missing 1 required positional argument: 'terminal2'
```

When I tried it in the Colab environment, it worked as expected! 
Thank you very much for your attentive support.
